name: diffinf
channels:
  - huggingface
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - accelerate=0.18.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.5.0=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - arrow-cpp=11.0.0=py310h7516544_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py310h06a4308_0
  - attrs=22.1.0=py310h06a4308_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - babel=2.11.0=py310h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py310h06a4308_0
  - cryptography=38.0.4=py310h9ce1e76_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datasets=2.14.4=py_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diffusers=0.18.2=pyhd8ed1ab_0
  - dill=0.3.7=py310h06a4308_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - filelock=3.12.2=pyhd8ed1ab_0
  - fire=0.5.0=pyhd8ed1ab_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py310h5eee18b_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - future=0.18.3=pyhd8ed1ab_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_1
  - glib=2.69.1=he621ea3_2
  - glog=0.5.0=h2531618_0
  - grpc-cpp=1.46.1=h33aed49_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - huggingface_hub=0.16.4=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - ipykernel=6.19.2=py310h2f386ee_0
  - ipython=8.8.0=py310h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - jpeg=9e=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.16.0=py310h06a4308_0
  - jupyter=1.0.0=py310h06a4308_8
  - jupyter_client=7.4.8=py310h06a4308_0
  - jupyter_console=6.4.4=py310h06a4308_0
  - jupyter_core=5.1.1=py310h06a4308_0
  - jupyter_server=1.23.4=py310h06a4308_0
  - jupyterlab=3.5.3=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.16.5=py310h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=15_linux64_openblas
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=15_linux64_openblas
  - libclang=10.0.1=default_hb85057a_2
  - libcurl=8.1.1=h91b91d3_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=15_linux64_openblas
  - libllvm10=10.0.1=hbcb73fb_5
  - libnghttp2=1.52.0=ha637b67_1
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h0d84882_2
  - libtiff=4.5.0=h6a678d5_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lxml=4.9.1=py310h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mistune=0.8.4=py310h7f8727e_1000
  - multidict=6.0.2=py310h5eee18b_0
  - multiprocess=0.70.14=py310h06a4308_0
  - nbclassic=0.4.8=py310h06a4308_0
  - nbclient=0.5.13=py310h06a4308_0
  - nbconvert=6.5.4=py310h06a4308_0
  - nbformat=5.7.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - notebook=6.5.2=py310h06a4308_0
  - notebook-shim=0.2.2=py310h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.4=py310h757a811_1
  - numpy=1.22.3=py310h4ef5377_2
  - openblas=0.3.20=pthreads_h320a7e8_0
  - openssl=1.1.1v=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=22.0=py310h06a4308_0
  - pandas=1.5.3=py310h1128e8f_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py310h6a678d5_0
  - pip=22.3.1=py310h06a4308_0
  - platformdirs=2.5.2=py310h06a4308_0
  - ply=3.11=py310h06a4308_0
  - prometheus_client=0.14.1=py310h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=11.0.0=py310h468efa6_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310h06a4308_0
  - python-xxhash=2.0.2=py310h5eee18b_1
  - python_abi=3.10=2_cp310
  - pytorch=1.12.1=cpu_py310h9dbd814_1
  - pytz=2022.7=py310h06a4308_0
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=23.2.0=py310h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtconsole=5.4.0=py310h06a4308_0
  - qtpy=2.2.0=py310h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py310h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - sacremoses=master=py_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py310h06a4308_1
  - soupsieve=2.3.2.post1=py310h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py310h06a4308_0
  - tinycss2=1.2.1=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.13.2=py310he7d60b5_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.2=py310h5eee18b_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py310h06a4308_0
  - transformers=4.29.2=py310h06a4308_0
  - typing-extensions=4.4.0=py310h06a4308_0
  - typing_extensions=4.4.0=py310h06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.14=py310h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=0.58.0=py310h06a4308_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py310h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py310h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - altgraph==0.17.3
    - beartype==0.16.4
    - denoising-diffusion-pytorch==1.5.4
    - ema-pytorch==0.3.0
    - imageio==2.28.1
    - lazy-loader==0.2
    - pyarmor==8.3.3
    - pyarmor-cli-core==4.3.1
    - pyinstaller==5.13.0
    - pyinstaller-hooks-contrib==2023.6
    - pyparsing==3.0.9
    - pyqt5-sip==12.11.0
    - pywavelets==1.4.1
    - scikit-image==0.20.0
    - termcolor==2.2.0
    - tifffile==2023.4.12
    - torch-fidelity==0.3.0
prefix: /home/fe/nobis/anaconda3/envs/diffinf
